//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtnrOCSParkUsageInfo
    {
        public string useDt { get; set; }
        public byte[] patientNumber { get; set; }
        public int seq { get; set; }
        public string visitCode { get; set; }
        public string carNo { get; set; }
        public string useTm { get; set; }
        public string parkKey { get; set; }
        public string memo { get; set; }
        public string regId { get; set; }
        public string regDtm { get; set; }
        public string updtId { get; set; }
        public string updtDtm { get; set; }
    }
}
