//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtnrIoCarPtcl
    {
        public string parkNo { get; set; }
        public string inCarDt { get; set; }
        public string inCarSeqNo { get; set; }
        public string carNo { get; set; }
        public string carNo4 { get; set; }
        public string carKnd { get; set; }
        public string inCarNoRecogTy { get; set; }
        public string inNiceMacNo { get; set; }
        public string inCarTm { get; set; }
        public string inParkCustTy { get; set; }
        public string inImagePath { get; set; }
        public string inRgTkGrpNm { get; set; }
        public string outNiceMacNo { get; set; }
        public string outCarDt { get; set; }
        public string outCarTm { get; set; }
        public string outParkCustTy { get; set; }
        public string outImagePath { get; set; }
        public string outRgTkGrpNm { get; set; }
        public string fileNm1 { get; set; }
        public string fileCreateDt1 { get; set; }
        public Nullable<int> fileSize1 { get; set; }
        public string fileNm2 { get; set; }
        public string fileCreateDt2 { get; set; }
        public Nullable<int> fileSize2 { get; set; }
        public string smallCarTy { get; set; }
        public Nullable<System.DateTime> npmsInSendDtm { get; set; }
        public string npmsInSendRes { get; set; }
        public Nullable<System.DateTime> npmsOutSendDtm { get; set; }
        public string npmsOutSendRes { get; set; }
        public Nullable<System.DateTime> npmsInImgDtm { get; set; }
        public string npmsInImgRes { get; set; }
        public Nullable<System.DateTime> npmsOutImgDtm { get; set; }
        public string npmsOutImgRes { get; set; }
        public string carNoN { get; set; }
        public string manualPark { get; set; }
        public string plateLocTy { get; set; }
        public string machineParkNo { get; set; }
        public string forestInSendRes { get; set; }
        public string forestOutSendRes { get; set; }
        public string areaNumber { get; set; }
        public string ansanTicketNo { get; set; }
        public string linkedCompanyPK { get; set; }
    }
}
