//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtnrMaintenance
    {
        public string parkNo { get; set; }
        public string maintenanceDt { get; set; }
        public string maintenanceTm { get; set; }
        public string maintenanceUsr { get; set; }
        public string niceMacNo { get; set; }
        public string maintenanceTy1 { get; set; }
        public string maintenanceTy2 { get; set; }
        public string maintenanceTy3 { get; set; }
        public string maintenanceTy4 { get; set; }
        public string maintenanceTy5 { get; set; }
        public string maintenanceTy6 { get; set; }
        public string maintenanceTy7 { get; set; }
        public string maintenanceTy8 { get; set; }
        public string maintenanceTy9 { get; set; }
        public string maintenanceTy10 { get; set; }
        public Nullable<System.DateTime> npmsInSendDtm { get; set; }
        public string npmsInSendRes { get; set; }
    }
}
