//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtnrLedSetInfo
    {
        public string parkNo { get; set; }
        public string inOutCarTy { get; set; }
        public string ledOutTy { get; set; }
        public string parkCustTy { get; set; }
        public string ledUpMsg { get; set; }
        public string ledDnMsg { get; set; }
        public string ledUpColor { get; set; }
        public string ledDnColor { get; set; }
        public string ledEffect { get; set; }
        public Nullable<int> ledSpeed { get; set; }
    }
}
