//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtnrRgTkIssuPtcl
    {
        public string parkNo { get; set; }
        public string regularTkNo { get; set; }
        public string rgTkGrpCd { get; set; }
        public string regularTkKnd { get; set; }
        public string regularTkUseYn { get; set; }
        public string regularTkStartDt { get; set; }
        public string regularTkEndDt { get; set; }
        public string regularTkCarNo { get; set; }
        public string carNo4 { get; set; }
        public string carMdl { get; set; }
        public string carClor { get; set; }
        public string carOwnrNm { get; set; }
        public string carOwnrCnttOfc { get; set; }
        public int timeLmtAplyTm { get; set; }
        public int regularTkMonAmt { get; set; }
        public string remark { get; set; }
        public string carNoN { get; set; }
        public string regularTkRegDt { get; set; }
        public string companyNm { get; set; }
        public string departmentNm { get; set; }
        public string bmsKey { get; set; }
    }
}
