//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtnrParkInfo
    {
        public string parkNo { get; set; }
        public string parkNm { get; set; }
        public string address { get; set; }
        public string businessNo { get; set; }
        public string businessNm { get; set; }
        public string presidentNm { get; set; }
        public string telNo { get; set; }
        public string maxChrgCalcMtd { get; set; }
        public string calculationUnit { get; set; }
        public string roundMtd { get; set; }
        public string preServiceTm { get; set; }
        public string parkStartTm { get; set; }
        public string parkEndTm { get; set; }
        public Nullable<int> discountTkTotUseCnt { get; set; }
        public Nullable<int> discountTkTotUseTm { get; set; }
        public string carryOffTy { get; set; }
        public string basicTm1ApyTy { get; set; }
        public string npmsConnTy { get; set; }
        public string nonlOCarPtclTy { get; set; }
        public string rgTkPassMacNo { get; set; }
        public string discountAfTy { get; set; }
        public Nullable<int> fullCarCnt { get; set; }
        public string fullCarCtrlTy { get; set; }
        public string fullCarCtrlLprTy { get; set; }
        public string barcode_useYn { get; set; }
        public string barcode_CpTy { get; set; }
        public string carFindTerm { get; set; }
        public string matchingDigit { get; set; }
        public string salesVehicleTy { get; set; }
        public string directionUseYn { get; set; }
        public string fullCarRegularPassTy { get; set; }
        public string pcmkCommTy { get; set; }
        public Nullable<int> pcmkCommMny { get; set; }
        public string fullCarCtrlDisplayTy { get; set; }
        public string fullCarWhnGtbarOpenYn { get; set; }
        public string homeNetTy { get; set; }
        public string timedisTy { get; set; }
        public string fullCarExcpRgTkty { get; set; }
        public string innerParkingTm { get; set; }
        public string discountTkKnd { get; set; }
        public string npmsMsgSrvIp { get; set; }
        public string npmsMsgSrvPort { get; set; }
        public string npmsImgSrvIp { get; set; }
        public string npmsImgSrvPort { get; set; }
        public string kioskTotalSystem { get; set; }
        public Nullable<int> oneDayAmt { get; set; }
        public string fullCountCompanyCd { get; set; }
        public string pcmkDiscountTy { get; set; }
        public string errRtnCarAplyYn { get; set; }
        public Nullable<int> errRtnCarAdtnAplyTm { get; set; }
        public Nullable<int> errJudgTm { get; set; }
        public string calPartTy { get; set; }
        public string taxTy { get; set; }
        public string nonPaidYn { get; set; }
        public string nonPaidDtm { get; set; }
        public string satNonPaidDtm { get; set; }
        public string nonPaidPayYn { get; set; }
    }
}
