//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtnrAPTHomeNetInfo
    {
        public string parkNo { get; set; }
        public int homeNetSeq { get; set; }
        public string homeNetCompany { get; set; }
        public string homeNetCommTy { get; set; }
        public string homeNetDeviceTy { get; set; }
        public string homeNetIP { get; set; }
        public Nullable<int> homeNetPort { get; set; }
        public string homeNetComPort { get; set; }
        public string homeNetVer { get; set; }
        public string homeNetID { get; set; }
        public string homeNetPW { get; set; }
        public string localServerIP { get; set; }
        public Nullable<int> localServerPort { get; set; }
    }
}
