//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtnrWorkingClosePtcl
    {
        public string parkNo { get; set; }
        public string startWorkDt { get; set; }
        public string workingSeqNo { get; set; }
        public Nullable<int> adjCnt { get; set; }
        public Nullable<int> originalParkAmt { get; set; }
        public Nullable<int> discountCnt { get; set; }
        public Nullable<int> discountTkUseCnt { get; set; }
        public Nullable<int> discountAmt { get; set; }
        public Nullable<int> cashSaleCnt { get; set; }
        public Nullable<int> cashSaleAmt { get; set; }
        public Nullable<int> cardSaleCnt { get; set; }
        public Nullable<int> cardSaleAmt { get; set; }
        public Nullable<int> saleCnt { get; set; }
        public Nullable<int> saleAmt { get; set; }
        public Nullable<int> nomalOutCarCnt { get; set; }
        public Nullable<int> regularTkOutCarCnt { get; set; }
        public Nullable<int> chargeDcCnt { get; set; }
        public Nullable<int> returnCarFreeCnt { get; set; }
        public Nullable<int> pcmkCloseCnt { get; set; }
        public Nullable<int> pcmkCloseAmt { get; set; }
        public Nullable<System.DateTime> npmsSendDtm { get; set; }
        public Nullable<System.DateTime> npmsSendRes { get; set; }
    }
}
