//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtnrCashSendClosePtcl
    {
        public string parkNo { get; set; }
        public string niceMacNo { get; set; }
        public string cashSendDt { get; set; }
        public string cashSendTm { get; set; }
        public string preCashSendDt { get; set; }
        public string preCashSendTm { get; set; }
        public Nullable<int> cashSaleCnt { get; set; }
        public Nullable<int> cashSaleAmt { get; set; }
        public Nullable<int> cashInAmt { get; set; }
        public Nullable<int> cashOutAmt { get; set; }
        public Nullable<int> incw54 { get; set; }
        public Nullable<int> incw14 { get; set; }
        public Nullable<int> incw53 { get; set; }
        public Nullable<int> incw13 { get; set; }
        public Nullable<int> outcw14 { get; set; }
        public Nullable<int> outcw53 { get; set; }
        public Nullable<int> outcw13 { get; set; }
        public Nullable<int> cashFailOutAmt { get; set; }
        public Nullable<System.DateTime> npmsSendDtm { get; set; }
        public string npmsSendRes { get; set; }
    }
}
