//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtnrRgtGrpSetInfo
    {
        public string parkNo { get; set; }
        public string rgTkGrpCd { get; set; }
        public string rgTkGrpNm { get; set; }
        public string regularTkKnd { get; set; }
        public Nullable<int> regularTkMonAmt { get; set; }
        public string useYn { get; set; }
        public string ledUpMsgIn { get; set; }
        public string ledDnMsgIn { get; set; }
        public string ledUpMsgOut { get; set; }
        public string ledDnMsgOut { get; set; }
    }
}
