//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtnrDisPtcl
    {
        public string parkNo { get; set; }
        public string inCarDt { get; set; }
        public string inCarSeqNo { get; set; }
        public string chargeSeqNo { get; set; }
        public int discountSeq { get; set; }
        public string discountMtd { get; set; }
        public string discountTkKnd { get; set; }
        public string niceMacNo { get; set; }
        public string discountApplyDt { get; set; }
        public string discountApplyTm { get; set; }
        public Nullable<int> discountAmt { get; set; }
        public string discountTkSerialNo { get; set; }
        public string discountShpCd { get; set; }
        public string webDisShpCd { get; set; }
        public string cause { get; set; }
    }
}
