//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtnrAPTParkInfo
    {
        public string parkNo { get; set; }
        public int seq { get; set; }
        public string doubleParkTy { get; set; }
        public Nullable<int> doubleFindTerm { get; set; }
        public string NvehicleDivViolation { get; set; }
        public string RvehicleDivViolation { get; set; }
        public string vehicleDivOpTime { get; set; }
        public string vehicleDivUseYn { get; set; }
        public string vehicleDivExcDay { get; set; }
        public string isCmrclCar { get; set; }
        public string vehicleDivMacTy { get; set; }
        public string vehicleDivOpDt { get; set; }
        public string vehicleDivRgTkGrp { get; set; }
    }
}
