//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtnrMacDtlInfo
    {
        public string parkNo { get; set; }
        public string niceMacNo { get; set; }
        public string deviceCardCOMPort { get; set; }
        public string deviceDisCOMPort { get; set; }
        public string devicePrintCOMPort1 { get; set; }
        public string devicePrintCOMPort2 { get; set; }
        public string deviceBarcodeCOMPort { get; set; }
        public string deviceCashInCOMPort { get; set; }
        public string deviceCashOutCOMPort { get; set; }
        public string deviceConnLprMacNo { get; set; }
        public string deviceConnLEDMacNo { get; set; }
        public string deviceBarrierCOMPort { get; set; }
        public string deviceCtlCOMPort { get; set; }
        public string deviceCashCnt { get; set; }
        public string vanCo { get; set; }
        public string devicePlcComPort { get; set; }
        public string deviceSignalLightCOMPort { get; set; }
        public string deviceDirectionCOMPort { get; set; }
        public string t2deviceBarrierCOMPort { get; set; }
        public string t2deviceDirectionCOMPort { get; set; }
        public string fullLedComPort { get; set; }
        public string deviceLightCarCOMPort { get; set; }
        public string parkAreaDeviceID { get; set; }
        public string fullSignalLightCOMPort { get; set; }
        public string deviceOutDirectionCOMPort1 { get; set; }
        public string deviceOutDirectionCOMPort2 { get; set; }
        public string powerOffDeviceMacNo { get; set; }
        public string powerOffDeviceCOMPort { get; set; }
        public string fullLed2ComPort { get; set; }
        public string fullLed3ComPort { get; set; }
    }
}
