//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtnrChrgSctSetInfo
    {
        public string parkNo { get; set; }
        public string dayTy { get; set; }
        public string chrgKnd { get; set; }
        public string chrgDtlInfo { get; set; }
        public string sectionTy { get; set; }
        public string sectionStartTm { get; set; }
        public string sectionEndTm { get; set; }
        public string dayNightTy { get; set; }
        public Nullable<int> basicTm { get; set; }
        public Nullable<int> basicChrg { get; set; }
        public Nullable<int> unitTm { get; set; }
        public Nullable<int> unitChrg { get; set; }
        public Nullable<int> unitCnt { get; set; }
        public Nullable<int> additionalUnitTm { get; set; }
        public Nullable<int> additionalUnitChrg { get; set; }
        public Nullable<int> additionalUnitCnt { get; set; }
        public Nullable<int> additionalUnitTm2 { get; set; }
        public Nullable<int> additionalUnitChrg2 { get; set; }
        public Nullable<int> additionalUnitCnt2 { get; set; }
        public Nullable<int> additionalUnitTm3 { get; set; }
        public Nullable<int> additionalUnitChrg3 { get; set; }
        public Nullable<int> addFixChrg { get; set; }
    }
}
