//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtnrRgTkExtPtcl
    {
        public string parkNo { get; set; }
        public string regularTkNo { get; set; }
        public string settlementDt { get; set; }
        public string settlementTm { get; set; }
        public string niceMacNo { get; set; }
        public string carNo { get; set; }
        public string regularTkExtTy { get; set; }
        public string regularTkStartDt { get; set; }
        public string regularTkEndDt { get; set; }
        public Nullable<int> regularTkExtAmt { get; set; }
        public string creditCardNo { get; set; }
        public string approveNo { get; set; }
        public string approveDt { get; set; }
        public string approveTm { get; set; }
        public Nullable<System.DateTime> npmsSendDtm { get; set; }
        public string npmsSendRes { get; set; }
        public string payTy { get; set; }
        public string purchaseNm { get; set; }
        public string purchaseCd { get; set; }
        public string IssuerNm { get; set; }
        public string IssuerCd { get; set; }
        public string kisVanKey { get; set; }
        public string storeNo { get; set; }
    }
}
