//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtnrLocalGovCalPart
    {
        public string parkNo { get; set; }
        public string parkStartTm { get; set; }
        public string parkEndTm { get; set; }
        public string freeParkStartTm { get; set; }
        public string freeParkEndTm { get; set; }
        public Nullable<int> basicTm { get; set; }
        public Nullable<int> basicChrg { get; set; }
        public Nullable<int> unitTm { get; set; }
        public Nullable<int> unitChrg { get; set; }
        public Nullable<int> returnCarTm { get; set; }
        public Nullable<int> dayMaxChrg { get; set; }
        public string satParkStartTm { get; set; }
        public string satParkEndTm { get; set; }
    }
}
