//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtnrAPTIoCarPtcl
    {
        public string parkNo { get; set; }
        public string inCarDt { get; set; }
        public string inCarSeqNo { get; set; }
        public string inRgTkGrpNm { get; set; }
        public string inRgTkGrpDong { get; set; }
        public string inRgTkGrpHo { get; set; }
        public string inRgTkCarColor { get; set; }
        public string inRgTkCarMdl { get; set; }
        public string inRgTkHomeNetSendYn { get; set; }
        public string outRgTkHomeNetSendYn { get; set; }
        public string vehicleDivViolation { get; set; }
        public string vehicleDivMemo { get; set; }
    }
}
