//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtnrNonInCarPtcl
    {
        public string parkNo { get; set; }
        public string inCarDt { get; set; }
        public string inCarSeqNo { get; set; }
        public string carNo { get; set; }
        public string carNo4 { get; set; }
        public string carKnd { get; set; }
        public string inCarNoRecogTy { get; set; }
        public string inNiceMacNo { get; set; }
        public string inCarTm { get; set; }
        public string inParkCustTy { get; set; }
        public string inImagePath { get; set; }
        public string inRgTkGrpNm { get; set; }
        public string smallCarTy { get; set; }
        public string carNoN { get; set; }
        public string manualPark { get; set; }
        public string machineParkNo { get; set; }
        public string areaNumber { get; set; }
        public string ansanTicketNo { get; set; }
        public string linkedCompanyPK { get; set; }
    }
}
