//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_InOutList
    {
        public string 차량번호 { get; set; }
        public string 입차일자 { get; set; }
        public string 입차시간 { get; set; }
        public string 출차일자 { get; set; }
        public string 출차시간 { get; set; }
        public string 입차장비번호 { get; set; }
        public string 입차장비명 { get; set; }
        public string 출차장비번호 { get; set; }
        public string 출차장비명 { get; set; }
        public string 정기권그룹명 { get; set; }
        public string 정기권그룹코드 { get; set; }
        public string 고객구분코드 { get; set; }
        public string 고객구분 { get; set; }
        public string 고객_동_ { get; set; }
        public string 고객_호_ { get; set; }
        public string 차량색상 { get; set; }
        public string 차량모델 { get; set; }
        public string 홈네트워킹사용여부 { get; set; }
        public string 입차이미지경로 { get; set; }
        public string 입차파일명 { get; set; }
        public string 출차이미지경로 { get; set; }
        public string 출차파일명 { get; set; }
    }
}
