//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Sewon_InOut
    {
        public string 구분 { get; set; }
        public string 입차기기 { get; set; }
        public string 입차기기명 { get; set; }
        public string 입차일자 { get; set; }
        public string 입차시간 { get; set; }
        public string 입차번호 { get; set; }
        public string 출차기기 { get; set; }
        public string 출차기기명 { get; set; }
        public string 출차일자 { get; set; }
        public string 출차시간 { get; set; }
        public string 출차번호 { get; set; }
        public string 출차상태 { get; set; }
        public string 회사명 { get; set; }
        public string 부서명 { get; set; }
    }
}
