//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpmuApartment_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Sewon_Reg
    {
        public string 그룹 { get; set; }
        public string 이름 { get; set; }
        public string 연락처 { get; set; }
        public string 차량번호 { get; set; }
        public string 회사명 { get; set; }
        public string 부서명 { get; set; }
        public string 등록일자 { get; set; }
        public string 사용유무 { get; set; }
        public string 유효기간시작일 { get; set; }
        public string 유효기간종료일 { get; set; }
        public string 마지막방문일자 { get; set; }
        public string 마지막출차시간 { get; set; }
        public string 입차상태 { get; set; }
    }
}
